Added more user roles to fakedata
NextUp-comedy/db-models-nc pull request #4
Opened 2022-08-11 11:42 UTC by zaher-aa

2022-08-11 11:49 UTC, Ibrahim-Jarada approved these changes

2022-08-11 12:00 UTC, RandSohail approved these changes

2022-08-11 12:02 UTC, AymanSami98 approved these changes

2022-08-11 12:16 UTC, Jood80 requested changes

2022-08-11 12:16 UTC, Jood80 commented on src/database/fakeData/index.ts
> +    image: 'data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==',
Nope. this image value will be the uploaded string coming from `s3` service. Remember, the `updateUser` DTO will have the image in `base46` but we won't store it in the database like that

2022-08-11 12:16 UTC, Jood80 commented on src/database/fakeData/index.ts
> +    name: 'master_admin',
Is the `master_admin` the same as `system_admin` or `admin`?

2022-08-11 12:24 UTC, Jood80 commented on src/database/fakeData/index.ts
> +    image: 'data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==',
Add this picture for instance 😁 
https://nextup-comedy-bucket-gfs.s3.eu-west-2.amazonaws.com/2/1660034083405.jpeg

2022-08-14 11:57 UTC, zaher-aa commented on src/database/fakeData/index.ts
> +    image: 'data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==',
Ok, its a nice picture 😇

2022-08-15 07:12 UTC, zaher-aa commented on src/database/fakeData/index.ts
> +    name: 'master_admin',
Yes its the same, the founders named it `master_admin`

2022-08-15 07:43 UTC, Jood80 approved these changes

2022-08-15 07:58 UTC, Jood80 approved these changes

2022-08-15 07:59 UTC, merged